version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        NODE_VERSION: '16-alpine3.14'
        YARN_VERSION: '3.1.1'
    container_name: node
    stdin_open: true
    tty: true
    environment:
      HISTFILE: .dockerdev/.ash_history
    volumes:
      - .dockerdev/.profile:/root/.profile:ro
      - .dockerdev/.ashrc:/root/.ashrc
      - yarn:/usr/src/.yarn
      - .yarnrc.yml:/usr/src/.yarnrc.yml
      - .:/usr/src:cached
    command: >
      ash -c "source /root/.profile &&
      yarn &&
      /bin/ash"

volumes:
  yarn:
